### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by markusressel** [femueller/python-n26#12]
Hi,

great library! :-)
I am in the process of creating a custom component for [Home Assistant](https://home-assistant.io) so N26 banking data can be used as a sensor in Home Assistant. I already have a working prototype that can show various balance properties and I assume I will be able to create a PR for it (on the Home Assistant repo) in the coming days/weeks.

I am opening this issue just to inform you about this, as this might bring a little more attention to your library :) And I would also like to include you in the PRs so the author of this library (you) can have a look at my implementation and if there is something to improve - especially in the documentation.

**Comment by femueller** [comment]
Hey @markusressel!
thanks for your feedback 🙂.

I haven't looked much into Home Assistant but I will definitely. Supporting querying of n26 data sounds very interesting to me and I would love to support it.

Let's keep up the conversation about it

**Comment by markusressel** [comment]
I'm glad to hear that! I wasn't sure if you still maintain this repo.

I saw that you have an open issue for querying spaces (#9). I would really like to have the ability to track spaces via home assistant too. Is there a chance you will have the time to implement this anytime soon? Otherwise I would try to do it and open a PR here. If possible I would like to have this implemented first so the initial release of the custom component supports all the things right out of the box and I can save myself some PR headache on the home assistant side of things :grin:

**Comment by femueller** [comment]
I still maintain it but didn't make the time to push additional improvements.

If you want to contribute the spaces feature, feel free to as I can not promise to implement it right now. However, if I'll find the time I will definitely add it if people find it useful in the near future.
It was just not that obvious to me since I am not really using spaces at this point myself 🙂.

**Comment by markusressel** [comment]
I ran into api rate limiting constraints when testing.
To mitigate that I changed the code for the authentication token to reuse it and (if necessary) refresh it.
This only applies to API usage though as CLI calls will always create a new `Api` instance and therefore can't refresh this token (they simply don't have it anymore).
See #15

**Comment by femueller** [comment]
Just merged your PR and created a new release 👍

**Comment by markusressel** [comment]
I've created a PR on Home Assistant just now.
https://github.com/home-assistant/home-assistant/pull/21920

**Comment by markusressel** [comment]
I made a little mistake when implementing the `refresh_token` feature that prevents Api usage over longer periods of time :disappointed: . I have already fixed this, please have a look at #16 :nerd_face:

**Comment by femueller** [comment]
@markusressel I've just merged it and created a new release

**Comment by markusressel** [comment]
Nice, I think if you can create a release of the current state and I have adapted the hass component we can merge the first version of it :nerd_face:

**Comment by femueller** [comment]
Not all commands for the CLI work right now @markusressel. Once they work again I will create a new release. For example: `n26 info`.

**Comment by markusressel** [comment]
@femueller I'm sorry to hear that, I tested everything on my account. I guess there may be attributes that can be missing on other accounts, or are there other issues with the code?

**Comment by markusressel** [comment]
@femueller I think it would be the best to add tests with mocked API responses to test for such kind of errors. Can you capture the API response you get with your account (optimally for all api endpoints) and simply write the original `json` string to a text file? Of course **remember to "obfuscate" any data that may relate to your account** but keep the general structure of the json.

I have done the same thing on my [xs1-api-client library](https://github.com/markusressel/xs1-api-client/tree/master/tests/api_responses). If you want you can just add those sample responses and let me add some tests for all the requests (to save you some time) and add `json` responses that I got from my account to account for all possible situations.

**Comment by femueller** [comment]
> @femueller I'm sorry to hear that, I tested everything on my account. I guess there may be attributes that can be missing on other accounts, or are there other issues with the code?

I'll have to figure out later today if it's an issue on my end.

And I agree 🙂...as the adoption of the module grows testing should be also extended.

**Comment by femueller** [comment]
@markusressel I guess we can close this issue for now?

**Comment by markusressel** [comment]
@femueller Yes, the last thing thats missing is the PR at home assistant :+1:

**Comment by markusressel** [comment]
Hey, just leaving als comment that this is now finally live in Home Assistant.
https://www.home-assistant.io/blog/2019/04/24/release-92/

**Comment by jjprz** [comment]
@markusressel @femueller N26 integration in home assistant has been removed. Is there any way to create a custom component?

**Comment by markusressel** [comment]
Sadly not at the moment. 2FA is required every 2 hours, which makes it pretty much impossible to have a background service constantly polling the N26 api.
