### ISSUE TITLE
problem with auth

### ISSUE THREAD

**Issue by mschultheiss83** [femueller/python-n26#129]
`BASE_URL_GLOBAL = 'https://api.tech26.global'` is not working for me

i replaced it with `BASE_URL_GLOBAL = 'https://api.tech26.de'`

**Comment by mschultheiss83** [comment]
see https://github.com/femueller/python-n26/pull/127 for details

**Comment by markusressel** [comment]
Hey @mschultheiss83, please try version 3.3.1 .

**Comment by markusressel** [comment]
Closing as duplicate of #125
