### ISSUE TITLE
Write Unit tests

### ISSUE THREAD

**Issue by femueller** [femueller/python-n26#3]
Code should be properly tested for version 1.0.

**Comment by sublinus** [comment]
Hi @femueller,

I really like the project and would like to write the tests, but i'm not sure how to proceed.
- Do you want to test api and config?
- Do you want to mock the n26 endpoints for api test?
- What module would you want to use for testing? I would personally suggest using pytest.

**Comment by femueller** [comment]
Hey @sublinus,

thanks for your feedback and your contribution is definitely welcome!

As this is one of my first Python projects I know that there is still lots of stuff to improve and many things might be imperfect at this point.

To answer your questions:

> Do you want to test api and config?
Yes, I'd like to test both.

> Do you want to mock the n26 endpoints for api test?
Mocking the API was my main idea behind this issue, so yes.

> What module would you want to use for testing? I would personally suggest using pytest.
I would agree using pytest would be also my preference.

**Comment by femueller** [comment]
Considering this issue for now as done. Since @markusressel has implemented now the most important tests.
