### ISSUE TITLE
error: 'invalid_client'

### ISSUE THREAD

**Issue by knandraina** [femueller/python-n26#42]
Hi Felix, 

I got an error when I try to put my credentials. I would like to get my access token but it does not work when I run my code.

It works perfectly when I do it through curl request 
```
curl -k -H "Authorization:Basic bXktdHJ1c3RlZC13ZHBDbGllbnQ6c2VjcmV0" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&username=email&password=pwd" -X POST https://api.tech26.de/oauth/token
```

But This code does not work:

```
const instance = axios.create({
    baseURL: 'https://api.tech26.de',
    headers: {
        'Authorization': 'Basic bXktdHJ1c3RlZC13ZHBDbGllbnQ6c2VjcmV0',
    }
});

async function main() {
    try {
        const authentification_successful = await instance.post('/oauth/token',{ 
            username: 'secret',
            password: 'secret',
            grant_type: 'password'
        })
        console.log(authentification_successful)
    } catch (e) {
        console.log(e, e.response.data)
    }
}
main()
```

```
userMessage: 
   { title: 'error.oauth2.invalid_client.title',
     detail: 'error.oauth2.invalid_client.detail' },
  error: 'invalid_client',
  error_description: 'Unauthorized grant type: client_credentials' }
```

DO you have any idea what's wrong?
Knandraina

**Comment by markusressel** [comment]
Well at first sight:
1. you do not specify the content type
2. you use different `grant_type`

**Comment by knandraina** [comment]
I found out my mistake! 
{ 
            username: 'secret',
            password: 'secret',
            grant_type: 'password'
        }
they must be passed into params not body.

I had to modify the code like that:   const authentification_successful = await instance.post('/oauth/token',null,{ 
            username: 'secret',
            password: 'secret',
            grant_type: 'password'
        })
