### ISSUE TITLE
Transaction search

### ISSUE THREAD

**Issue by SoftCreatR** [femueller/python-n26#61]
In the past, we used https://github.com/PierrickP/n26 for automatic transaction processing. As described in their [API documentation](http://pierrickpaul.fr/n26/Account.html#transactions), the transactions method allowed to provide a search string, so you were able to search for transactions with specific texts (e.g. an invoice number).

I would like to see a similar function in your package, as this is the currently only n26 client, that actually works.

Thank you.

**Comment by markusressel** [comment]
This is already possible using the `--text-filter` parameter (if it didn't break recently).

**Comment by SoftCreatR** [comment]
It does, ty. Just came across `n26 transactions --help` 😄  Just one more thing: Would it be possible to get a JSON output (as alternative to the default output) for all responses? That would make working with your lib way easier (at least, for me).

Keep up the good work.

**Comment by markusressel** [comment]
Not using the CLI, no, but that would be an interesting thing to do.
You can directly use the Api in a little python script if you want to get a dictionary that you can easily convert to a json.

**Comment by SoftCreatR** [comment]
First, i'll have to learn Python 😄 I guess, i'll just create a parser/converter that fits my needs.

**Comment by markusressel** [comment]
@SoftCreatR As I have said, we can open an issue to print json instead of our custom output. I think it may very well be beneficial to other users as well.

However, if you think about creating a little python script it really isn't that complex (not to say you don't need to learn a few things):

```python
import json
from n26.api import Api

api = Api()
statuses = api.get_balance()
json_data = json.dumps(statuses)
print(statuses)
```

**Comment by SoftCreatR** [comment]
Well, thank you again. I made it work:

```
import json
from n26.api import GET, BASE_URL_DE, Api

api = Api()
transactions = api._do_request(GET, BASE_URL_DE + '/api/smrt/transactions', {
	'from': None,
	'to': None,
	'limit': 20,
	'pending': None,
	'categories': None,
	'textFilter': 'Foo Bar Baz',
	'lastId': None
})

print(json.dumps(transactions))
```

**Comment by markusressel** [comment]
@SoftCreatR 
Just fyi:
* methods starting with an underscore are not meant to be used from outside of the class (they are essentially private) although you can still access them if you want to (like you did)
* if you use the `get_transactions(text_filter="Foo Bar Baz"` method on the `api` object you can shrink your code down to the size of mine and it will execute the same code as yours.

I opened an issue to support json output directly: #63

**Comment by SoftCreatR** [comment]
Saw that, ty. And yeah, i already figured that out :D
