### ISSUE TITLE
Catch expired authentication

### ISSUE THREAD

**Issue by SoftCreatR** [femueller/python-n26#62]
When storing the authentication data in a file and this authentication data expires, the client shows an exception (but waits for authentication using the N26 app):

```
ERROR:root:401 Client Error: Unauthorized for url: https://api.tech26.global/oauth/token
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/n26/api.py", line 297, in get_token
    token_data = self._refresh_token(refresh_token)
  File "/root/miniconda3/lib/python3.7/site-packages/n26/api.py", line 359, in _refresh_token
    response.raise_for_status()
  File "/root/miniconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tech26.global/oauth/token
```

Instead, a message should be displayed, telling that the token is expired and needs to be refreshed by re-authenticating the login using the N26 app.

**Comment by markusressel** [comment]
Thx for reporting.

Console output is a little rough in general. As mentioned in #52 I would also want to show a message that 2FA is in progress and a confirmation is awaited. These two should be fixed together.
