### ISSUE TITLE
Typo for unlimited transaction call

### ISSUE THREAD

**Issue by wasmitnetzen** [femueller/python-n26#7]
In the function between get_transactions(), there is a typo in the URL. It calls `/api/smrt/transaction` which should be `/api/smrt/transactions` (the s at the end is missing) at [api.py:88](https://github.com/femueller/python-n26/blob/f40635cc10ff52c40158c8faefa2057a2f92a78a/n26/api.py#L88).

**Comment by femueller** [comment]
Thanks for reporting. This will be fixed in the next release.
