### ISSUE TITLE
To which field refers time-settings

### ISSUE THREAD

**Issue by pexmar** [femueller/python-n26#80]
Hi,

thanks for that great API! I really like using it!

I have a short question regarding the `get_transactions()`-function. We have the option there to set from_time and to_time parameters. To which field in the output do they refer? 
To createdTS or confirm?

cheers
pexmar

**Comment by femueller** [comment]
Hello @pexmar,

thanks for your feedback! Happy that you like it.

From what I can tell and also after double checking its referring to the `createdTS` UNIX timestamp.
I am not really sure what `confirmed` shows, but it displays a different timestamp compared to the actual transaction time.

**Comment by pexmar** [comment]
Thank you very much @femueller. That is also what I assumed and observed. Thanks a lot for double checking! :-)
