### ISSUE TITLE
Cannot fully automate an n26 transaction retrieval process due to 2FA

### ISSUE THREAD

**Issue by bernardcosta** [femueller/python-n26#94]
Is there a way to extend the 2FA expiration time? I would like to fully automate the process of transaction retrieval, run it periodically without manual input.

Is the API able to set this? or any other way around it?

I realise this might not be an issue from the python-n26 codebase itself but it is an issue for me in general.

**Comment by markusressel** [comment]
Not that we are aware of. N26 would have to provide some kind of application tokens for that to work (and through that bypass the 2FA), which is very unlikely to happen __period__. See also #67. Sadly there is not much we can do about this. You could try to hijack the phone app, but obiously that's not a recommended thing to do.
