### ISSUE TITLE
Authentication error - 400 Bad credentials

### ISSUE THREAD

**Issue by novag** [femueller/python-n26#97]
Hi,

first of all, thanks for creating and maintaining this library. I am using it since 2019 and now suddenly it stopped working.
Authentication always fails with:
`ValueError: Unexpected response for initial auth request: {"status":400,"detail":"Bad credentials","type":"invalid_grant","userMessage":{"title":"Login failed!","detail":"Error! The email address or password is incorrect"},"error":"invalid_grant","error_description":"Bad credentials"}`

For debugging reasons I tried using the n26 command with the example config yaml file and also tried specifying everything using the environment variables. Both options do result in the same error. I copied and pasted the credentials to the n26 web interface which works fine. However the web interface now seems to use a graphql endpoint instead of the endpoints used here.

Did anyone experience the same thing?

Thanks.

**Comment by markusressel** [comment]
I just tested `n26 balance` with:
```
> n26 --version                                                                                                                                                                                                                                                               
n26, version 3.2.1
```

And it works just fine:
```
> n26 balance                                                                                                                                                                                                                                                                
Initiating authentication flow, please check your phone to approve login.
Authentication successful :)
XXXX.XX EUR
```

**Comment by novag** [comment]
Thanks, I already tried changing it to something without any special characters but the result is the same. I think it stopped working around the time I upgraded to python 3.9. Which python version do you use?

**Comment by markusressel** [comment]
```
> python --version
Python 3.9.1
```

Do you maybe have multiple configuration files that override each other? ENV variables should override everything else though... Not sure how we can help with this, seems like a configuration issue on your end :cry:

**Comment by novag** [comment]
No unfortunately not. The exact same config works on mac. But yes I agree looks like something specific to my environment thus I am closing this now. Thanks for your help!

**Comment by novag** [comment]
This is still a big mystery to me. I can log in from other devices without any problems. But even within a fresh container the initial authentication flow does not work on my main computer. I verified that the request goes to the exact same host as from my other computers.
In the end ignoring the global api endpoint and authenticating against api.tech26.de works fine. As soon as I authenticate against the global endpoint it does not work anymore.

**Comment by markusressel** [comment]
Is there some proxy/VPN etc. involved?

**Comment by novag** [comment]
No, nothing the like.

**Comment by novag** [comment]
Okay this is weird. The other computer was on a different network and I sometimes get a different name resolution from 9.9.9.9 for api.tech26.global.
The A record should point to 128.65.209.6. But sometimes I get the following triplet:
54.70.155.169
52.89.126.120
34.217.248.204

...
